### ISSUE TITLE
Error when installing git-stats

### ISSUE THREAD

**Issue by mrlzla** [IonicaBizau/git-stats#106]
/home/vladik/.npm-packages/bin/git-stats -> /home/vladik/.npm-packages/lib/node_modules/git-stats/bin/git-stats

> git-stats@2.10.0 postinstall /home/vladik/.npm-packages/lib/node_modules/git-stats
> node scripts/migration/2.0.0.js

/home/vladik/.npm-packages/lib/node_modules/git-stats/node_modules/bug-killer/node_modules/daty/node_modules/class-methods/node_modules/static-methods/lib/index.js:15
        name => name !== "name"
              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vladik/.npm-packages/lib/node_modules/git-stats/node_modules/bug-killer/node_modules/daty/node_modules/class-methods/lib/index.js:5:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by IonicaBizau** [comment]
Can you still reproduce this? Hopefully it was fixed after the latest `static-methods` publish.

**Comment by alukichev** [comment]
I ran into this same problem just a few minutes ago doing "npm install -g git-stats". "npm --version" gives 2.15.9, "node --version" gives v4.5.0 on my machine.

**Comment by alukichev** [comment]
After changes to static-methods mentioned in discussion [here](https://github.com/IonicaBizau/static-methods/commit/9a63d1da05d370e75d7ffefa20af1d5744a521b5#commitcomment-20229452), I cannot reproduce this issue.

**Comment by IonicaBizau** [comment]
Great! Thanks for suggestions, @alukichev! [`ship-release`](https://github.com/IonicaBizau/ship-release) wasn't updated on my machine and it had a bug before.

This article explains the process: https://ionicabizau.net/blog/33-how-i-npm

Cheers! 🍀
