### ISSUE TITLE
error installing on ubuntu 18

### ISSUE THREAD

**Issue by amandeepgautam** [IonicaBizau/git-stats#166]
I see the following error:

```
╰─ sudo npm i -g git-stats
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
/usr/bin/git-stats -> /usr/lib/node_modules/git-stats/bin/git-stats

> git-stats@2.10.13 postinstall /usr/lib/node_modules/git-stats
> node scripts/migration/2.0.0.js

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/usr/lib/node_modules/git-stats/scripts/migration/2.0.0.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/git-stats/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! git-stats@2.10.13 postinstall: `node scripts/migration/2.0.0.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-stats@2.10.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cohesity/.npm/_logs/2020-12-10T03_19_40_806Z-debug.log
```

I have npm version 6.14.8. Please let me know why the module is missing.

**Comment by amandeepgautam** [comment]
@iMagdy Can you take a look?

**Comment by amandeepgautam** [comment]
@iMagdy here is the StackOverflow link: https://stackoverflow.com/questions/65451697/cannot-find-module-error-on-installing-git-stats-on-ubuntu-using-npm

**Comment by iMagdy** [comment]
@amandeepgautam - I'm afraid I may not find enough time to check this out, I'll take a look as soon as I can, no timeframe though.

@IonicaBizau - Can you take a look at this?

**Comment by amandeepgautam** [comment]
@iMagdy Thanks. Still waiting for a resolution. Even a bounty on stackoverflow didn't help. Any pointers to what the problem can be will also be useful.

**Comment by IonicaBizau** [comment]
Hi @amandeepgautam! Sorry for the very late reply.
I just checked installing git-stats on my rpi2 and it worked fine.

Can you please post the output of **`ls /usr/lib/node_modules/git-stats/scripts/migration/`**?

Also, I highly recommend not installing npm packages using `sudo`.

**Comment by IonicaBizau** [comment]
I posted a longer answer on Stackoverflow: https://stackoverflow.com/a/65663214/1420197
